# We set the language to generic because python isn't supported on the MacOS X
# nodes on Travis. However, the language ends up being irrelevant anyway, since
# we install Python ourselves using conda.
language: generic

os:
    - osx
    - linux
    - windows

# Adding notifications since this is a project we otherwise don't update
# often, but need to make sure we see failures when they happen when
# running cron jobs.
notifications:
  email:
    recipients:
      - thomas.robitaille@gmail.com

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz

env:
  matrix:
    - PYTHON_VERSION=2.7 TOXENV='test'
    - PYTHON_VERSION=3.4 TOXENV='test-sphinx13'
    - PYTHON_VERSION=3.5 TOXENV='test-sphinx14'
    - PYTHON_VERSION=3.5 TOXENV='test-sphinx15'
    - PYTHON_VERSION=3.6 TOXENV='test-sphinx16'
    - PYTHON_VERSION=3.6 TOXENV='test-sphinx17'
    - PYTHON_VERSION=3.7 TOXENV='test-sphinx18'
    - PYTHON_VERSION=3.7 TOXENV='test-sphinx20'
    - PYTHON_VERSION=3.7 TOXENV='test-sphinxdev'

    # Make sure that things work even if the locale is set to C (which effectively means ASCII).
    # Some of the input rst files have unicode characters and we need to deal with this gracefully.
    - PYTHON_VERSION=2.7 TOXENV='test-clocale'
    - PYTHON_VERSION=3.7 TOXENV='test-clocale'

  global:
    - PIP_DEPENDENCIES="tox"
    - HOMEBREW_NO_AUTO_UPDATE=1

install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then brew install graphviz; fi
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - tox -e $TOXENV

after_success:
    - codecov
