# Most of the CI testing happens on Azure, but this configuration is for a
# regular cron job on Travis (as well as for pull requests).

language: c

os:
    - osx
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

addons:
    apt:
        packages:
            - graphviz

env:
  global:
    - CONDA_DEPENDENCIES="setuptools cython pytest-cov"
    - PIP_DEPENDENCIES="codecov"
    - HOMEBREW_NO_AUTO_UPDATE=1
    - PYTHON_VERSION=3.7

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then brew install graphviz; fi

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install git+https://github.com/sphinx-doc/sphinx.git

script:
    - py.test --cov sphinx_automodapi sphinx_automodapi -v

after_success:
    - codecov
