# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - osx
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz

env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.3
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5
  global:
    - CONDA_DEPENDENCIES="setuptools pytest sphinx cython pytest-cov"
    - PIP_DEPENDENCIES="coveralls"

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then brew update; brew install graphviz; fi

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - py.test --cov sphinx_automodapi sphinx_automodapi

after_success:
    - coveralls
